version: "3"
services:
  db:
    image: mdillon/postgis:11-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - local-db:/var/lib/postgresql/data

  web:
    build: .
    command: sleep infinity # python manage.py runserver_plus 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  local-db:
